default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rails_simple_web_development

test:
  <<: *default
  database: rails_simple_web_test

production:
  <<: *default
  database: rails_simple_web_production
  username: rails_simple_web
  password: <%= ENV['RAILS_SIMPLE_WEB_DATABASE_PASSWORD'] %>
